Update README.md

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -7,39 +7,28 @@ my-superuser chown -R root:root "${Distro_Specific_temp_path}"
 if [ -f "$Distro_Specific_path/info" ];then
 	. "$Distro_Specific_path/info"
 else
-	distro_name_="${1:-}"
+	distro_name="${1:-}"
 	PACKAGER="${2:-}"
-	if [ -z "${distro_name_}" ];then
+	if [ -z "${distro_name}" ];then
 		echo "checking your distro."
-		if [ -f /etc/os-release ];then
-			# freedesktop.org and systemd
-			. /etc/os-release
-			distro_name_="$ID"
-		elif [ -f /etc/lsb-release ];then
-			# For some versions of Debian/Ubuntu without lsb_release command
-			. /etc/lsb-release
-			distro_name_="$DISTRIB_ID"
-		else
-			# Fall back to uname, e.g. "Linux <version>", also works for BSD, etc.
-			distro_name_="$(uname -s)"
-		fi
-		echo "Using ${distro_name_}"
+		. "/usr/share/my_stuff/os-release"
+		echo "Using ${distro_name}"
 	fi
 
-	if ! . "${Distro_Specific_temp_path}/${distro_name_}/info" ;then
-		echo "failed to source : ${Distro_Specific_temp_path}/${distro_name_}/info"
+	if ! . "${Distro_Specific_temp_path}/${distro_name}/info" ;then
+		echo "failed to source : ${Distro_Specific_temp_path}/${distro_name}/info"
 		if ! . "${Distro_Specific_temp_path}/arch/info" ;then
 			echo "failed to source : ${Distro_Specific_temp_path}/arch/info"
 		fi
 	fi
 fi
 echo "creating Package-managers library file."
-cat "${Distro_Specific_temp_path}"/disto_package_manager/common | my-superuser tee "${Distro_Specific_temp_path}/${distro_name_}/Package-manager" >/dev/null 2>&1
+cat "${Distro_Specific_temp_path}"/disto_package_manager/common | my-superuser tee "${Distro_Specific_temp_path}/${distro_name}/Package-manager" >/dev/null 2>&1
 if [ "$PACKAGER" = "yay" ]; then
     PACKAGER="pacman"
 elif [ "$PACKAGER" = "paru" ]; then
     PACKAGER="pacman"
 fi
-cat "${Distro_Specific_temp_path}"/disto_package_manager/${PACKAGER}.sh | my-superuser tee -a "${Distro_Specific_temp_path}/${distro_name_}/Package-manager" >/dev/null 2>&1
-my-superuser cp -r "${Distro_Specific_temp_path}/${distro_name_}" "$Distro_Specific_path"
+cat "${Distro_Specific_temp_path}"/disto_package_manager/${PACKAGER}.sh | my-superuser tee -a "${Distro_Specific_temp_path}/${distro_name}/Package-manager" >/dev/null 2>&1
+my-superuser cp -r "${Distro_Specific_temp_path}/${distro_name}" "$Distro_Specific_path"
 
